# backend/domain/execution/order.py
"""Venue-agnostic order contracts."""

from __future__ import annotations

import enum
from dataclasses import dataclass
from datetime import datetime


class OrderSide(enum.StrEnum):
    """Direction of an order."""

    BUY = "buy"
    SELL = "sell"


def signed_volume(side: OrderSide, quantity: float) -> float:
    """Signed position volume: +quantity for longs, -quantity for shorts.

    Defined here (the base execution module) rather than in reconciliation so
    both :class:`Position` and the reconciliation contracts can share it
    without an import cycle.
    """
    return quantity if side is OrderSide.BUY else -quantity


def signed_direction(side: OrderSide) -> int:
    """Direction multiplier: +1 for BUY, -1 for SELL. Canonical single source."""
    return 1 if side is OrderSide.BUY else -1


class OrderType(enum.StrEnum):
    """Execution style of an order."""

    MARKET = "market"
    LIMIT = "limit"


class TimeInForce(enum.StrEnum):
    """Order lifetime policy."""

    GTC = "gtc"  # Good Till Cancelled
    IOC = "ioc"  # Immediate Or Cancel
    FOK = "fok"  # Fill Or Kill
    GTX = "gtx"  # Good Till Crossing (post-only)


class OrderStatus(enum.StrEnum):
    """Lifecycle status of an order.

    UNKNOWN is the explicit catch-all for a venue-reported state this system
    does not recognise. It must never be silently coerced into a meaningful
    state: an unrecognised venue status is a reconciliation problem, not a
    "new" or "done" order.
    """

    NEW = "new"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"
    UNKNOWN = "unknown"


@dataclass(frozen=True, slots=True)
class OrderRequest:
    """A request to place an order on any venue.

    Attributes
    ----------
    order_id: str
        Unique order identifier (generated by the application layer).
    proposal_id: str | None
        Proposal that generated this order, if any.
    symbol: str
        Market symbol.
    side: OrderSide
        Buy or sell.
    order_type: OrderType
        Market or limit.
    quantity: float
        Quantity to trade. Must be positive.
    limit_price: float | None
        Required when ``order_type`` is LIMIT.
    created_at: datetime
        Request creation timestamp (aware UTC).
    time_in_force: TimeInForce
        Order lifetime policy. Defaults to GTC.
    post_only: bool
        If True, order will only be placed as maker (post-only).
        Equivalent to time_in_force=GTX when True.
    """

    order_id: str
    proposal_id: str | None
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: float
    limit_price: float | None
    created_at: datetime
    time_in_force: TimeInForce = TimeInForce.GTC
    post_only: bool = False

    def __post_init__(self) -> None:
        if self.quantity <= 0:
            raise ValueError("order quantity must be positive")
        if self.order_type is OrderType.LIMIT and self.limit_price is None:
            raise ValueError("limit orders require a limit_price")
        if self.post_only and self.time_in_force is not TimeInForce.GTC:
            raise ValueError("post_only requires time_in_force=GTC (or use GTX directly)")
        if self.time_in_force is TimeInForce.GTX and not self.post_only:
            # GTX implies post_only
            object.__setattr__(self, "post_only", True)
